name: Upload File

on:
  workflow_dispatch:
    inputs:
        filename:
          description: 'File to upload'
          required: true
          default: 'file.txt'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload file
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_JSON }} > service-account.json
          echo "test content" > ${{ github.event.inputs.filename }}
          python upload.py ${{ github.event.inputs.filename }} ${{ secrets.FOLDER_ID }}
